version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET_NAME=app-transcription-bucket
      - USE_LOCALSTACK=true
    volumes:
      - ./env-config-generator.sh:/docker-entrypoint.d/env-config-generator.sh:ro
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
