version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - AWS_REGION=us-east-1
      - AWS_IDENTITY_POOL_ID=YOUR_IDENTITY_POOL_ID
      - S3_BUCKET_NAME=transcription-bucket
      - USE_LOCALSTACK=true
    volumes:
      - ./env-config-generator.sh:/docker-entrypoint.d/env-config-generator.sh:ro
